// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (CircleMember, error)
	AskForWPChangeByCircle(ctx context.Context, arg AskForWPChangeByCircleParams) (CircleMember, error)
	CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error)
	CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (CircleJoinRequest, error)
	CreateMood(ctx context.Context, arg CreateMoodParams) (Mood, error)
	DeleteCircle(ctx context.Context, id uuid.UUID) error
	DenyWPChangeAccessToCircle(ctx context.Context, arg DenyWPChangeAccessToCircleParams) (CircleMember, error)
	ExploreCirclesPaginated(ctx context.Context, arg ExploreCirclesPaginatedParams) ([]Circle, error)
	GetCircle(ctx context.Context, id uuid.UUID) (Circle, error)
	GetCircleMoods(ctx context.Context, circleID uuid.UUID) ([]Mood, error)
	GetCircleMoodsPaginated(ctx context.Context, arg GetCircleMoodsPaginatedParams) ([]Mood, error)
	GrantWPChangeAccessToCircle(ctx context.Context, arg GrantWPChangeAccessToCircleParams) (CircleMember, error)
	InviteToCircle(ctx context.Context, arg InviteToCircleParams) (CircleInvitation, error)
	KickFromCircle(ctx context.Context, arg KickFromCircleParams) error
	LeaveCircle(ctx context.Context, arg LeaveCircleParams) error
	ListInvitations(ctx context.Context, userID uuid.UUID) ([]Circle, error)
	ListJoinedCircles(ctx context.Context, memberID uuid.UUID) ([]Circle, error)
	ListRequestedCircles(ctx context.Context, userID uuid.UUID) ([]Circle, error)
	ReactToMood(ctx context.Context, arg ReactToMoodParams) (MoodReaction, error)
	RemoveInvitation(ctx context.Context, arg RemoveInvitationParams) error
	RemoveJoinRequest(ctx context.Context, arg RemoveJoinRequestParams) error
	RemoveReactToMood(ctx context.Context, arg RemoveReactToMoodParams) error
	SetCircleAccessToAdmin(ctx context.Context) (CircleMember, error)
	SetCircleAccessToPoster(ctx context.Context) (CircleMember, error)
	SetCircleAccessToViewer(ctx context.Context) (CircleMember, error)
	UpdateCircle(ctx context.Context, arg UpdateCircleParams) (Circle, error)
}

var _ Querier = (*Queries)(nil)
